# Generated by Django 4.0.3 on 2022-04-13 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_image_box_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_check', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='box_check',
        ),
    ]
